### ISSUE TITLE
Firefox extension doesn't work.

### ISSUE THREAD

**Issue by Shituation** [stevedecoded/youtube-upload-date#4]
It doesn't show anything. Also it would be nice to have some screenshots or a minimal description of what this extension (the chrome and firefox both) do. I don't even know what to expect, the time and date on the video description area? a button? whatever is supposed to happen, it didn't with the firefox extension.

**Comment by stevedecoded** [comment]
Which of these UIs does your YouTube video page have? YouTube are rolling out a new UI and this extension isn’t designed for it.

Old UI

![9D795C6C-7280-43A3-8435-9E5C1DCBFA8B](https://user-images.githubusercontent.com/673850/200163833-172432df-47b3-4c60-8e28-064e110c8c3f.jpeg)

New UI

<img width="812" alt="FECBE1A4-B6C6-41F9-9DCF-C87E6C23D911" src="https://user-images.githubusercontent.com/673850/200163868-0b3e1eb6-4353-47a5-8fb3-9cf2c4fa5b09.png">

There’s an active issue on this here https://github.com/stevedecoded/youtube-upload-date/issues/3

Also the Firefox port isn’t managed through  this repo, the code is privately held by @trevorraney and hasn’t been updated since 2.5 (the Chrome version is on 2.7). Best to contact through the Firefox extension page.

**Comment by Shituation** [comment]
I have the new UI. I still don't see the upload date on your screenshots (old ui), still don't know what to look for.
Closing this since firefox is not supported and the extension doesn't support the new UI either.

Thanks

**Comment by stevedecoded** [comment]
Feel free to close this again but I’m curious, you have the new YouTube video page UI but don’t see an upload date like in the second screenshot? I thought YouTube had updated their UI to show the video upload date without any extensions..

**Comment by Shituation** [comment]
The new UI shows an aproximate date, (aka "a day ago", "a week ago") not a day and not the TIME (which is what I needed)

random vid:
![sshot-002](https://user-images.githubusercontent.com/43975882/200175698-b46ce435-4dfe-4d7e-a781-054081e71c74.png)
